# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/christian/grpc_test

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/christian/grpc_test

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/christian/grpc_test/CMakeFiles /home/christian/grpc_test/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/christian/grpc_test/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named greeter

# Build rule for target.
greeter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 greeter
.PHONY : greeter

# fast build rule for target.
greeter/fast:
	$(MAKE) -f CMakeFiles/greeter.dir/build.make CMakeFiles/greeter.dir/build
.PHONY : greeter/fast

#=============================================================================
# Target rules for targets named helloworld_proto_lib

# Build rule for target.
helloworld_proto_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 helloworld_proto_lib
.PHONY : helloworld_proto_lib

# fast build rule for target.
helloworld_proto_lib/fast:
	$(MAKE) -f CMakeFiles/helloworld_proto_lib.dir/build.make CMakeFiles/helloworld_proto_lib.dir/build
.PHONY : helloworld_proto_lib/fast

greeter.o: greeter.cc.o
.PHONY : greeter.o

# target to build an object file
greeter.cc.o:
	$(MAKE) -f CMakeFiles/greeter.dir/build.make CMakeFiles/greeter.dir/greeter.cc.o
.PHONY : greeter.cc.o

greeter.i: greeter.cc.i
.PHONY : greeter.i

# target to preprocess a source file
greeter.cc.i:
	$(MAKE) -f CMakeFiles/greeter.dir/build.make CMakeFiles/greeter.dir/greeter.cc.i
.PHONY : greeter.cc.i

greeter.s: greeter.cc.s
.PHONY : greeter.s

# target to generate assembly for a file
greeter.cc.s:
	$(MAKE) -f CMakeFiles/greeter.dir/build.make CMakeFiles/greeter.dir/greeter.cc.s
.PHONY : greeter.cc.s

helloworld.grpc.pb.o: helloworld.grpc.pb.cc.o
.PHONY : helloworld.grpc.pb.o

# target to build an object file
helloworld.grpc.pb.cc.o:
	$(MAKE) -f CMakeFiles/helloworld_proto_lib.dir/build.make CMakeFiles/helloworld_proto_lib.dir/helloworld.grpc.pb.cc.o
.PHONY : helloworld.grpc.pb.cc.o

helloworld.grpc.pb.i: helloworld.grpc.pb.cc.i
.PHONY : helloworld.grpc.pb.i

# target to preprocess a source file
helloworld.grpc.pb.cc.i:
	$(MAKE) -f CMakeFiles/helloworld_proto_lib.dir/build.make CMakeFiles/helloworld_proto_lib.dir/helloworld.grpc.pb.cc.i
.PHONY : helloworld.grpc.pb.cc.i

helloworld.grpc.pb.s: helloworld.grpc.pb.cc.s
.PHONY : helloworld.grpc.pb.s

# target to generate assembly for a file
helloworld.grpc.pb.cc.s:
	$(MAKE) -f CMakeFiles/helloworld_proto_lib.dir/build.make CMakeFiles/helloworld_proto_lib.dir/helloworld.grpc.pb.cc.s
.PHONY : helloworld.grpc.pb.cc.s

helloworld.pb.o: helloworld.pb.cc.o
.PHONY : helloworld.pb.o

# target to build an object file
helloworld.pb.cc.o:
	$(MAKE) -f CMakeFiles/helloworld_proto_lib.dir/build.make CMakeFiles/helloworld_proto_lib.dir/helloworld.pb.cc.o
.PHONY : helloworld.pb.cc.o

helloworld.pb.i: helloworld.pb.cc.i
.PHONY : helloworld.pb.i

# target to preprocess a source file
helloworld.pb.cc.i:
	$(MAKE) -f CMakeFiles/helloworld_proto_lib.dir/build.make CMakeFiles/helloworld_proto_lib.dir/helloworld.pb.cc.i
.PHONY : helloworld.pb.cc.i

helloworld.pb.s: helloworld.pb.cc.s
.PHONY : helloworld.pb.s

# target to generate assembly for a file
helloworld.pb.cc.s:
	$(MAKE) -f CMakeFiles/helloworld_proto_lib.dir/build.make CMakeFiles/helloworld_proto_lib.dir/helloworld.pb.cc.s
.PHONY : helloworld.pb.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... greeter"
	@echo "... helloworld_proto_lib"
	@echo "... rebuild_cache"
	@echo "... greeter.o"
	@echo "... greeter.i"
	@echo "... greeter.s"
	@echo "... helloworld.grpc.pb.o"
	@echo "... helloworld.grpc.pb.i"
	@echo "... helloworld.grpc.pb.s"
	@echo "... helloworld.pb.o"
	@echo "... helloworld.pb.i"
	@echo "... helloworld.pb.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

